### ISSUE TITLE
[BUG] [ws-tool-name] Error while transfer policies which including "Requires Review"

### ISSUE THREAD

**Issue by thestift** [whitesource-ps/ws-copy-policy#13]
Hi,
I think I found a bug:

**Bug Description**  
Getting an error message during execution
````
$ ws_copy_policy -u https://saas-eu.whitesourcesoftware.com/api -k ${WS_USERKEY} -o ${WS_APIKEY} -s project -t 5
starting...
validating parameters
using url https://saas-eu.whitesourcesoftware.com/api
found destination project: xxxx. Key value: cloud_backend
found destination project: xxxx. Key value: cloud_backend
found source project: Cloud Backend. Key value: cloud_backend
TOTAL: 2 projects have a destination tag value and should be handled
handling 1 out of the 2 projects.
adding policy Unknown Licenses to the project xxxxx
Error code: 3012
Error message: Invalid license id: -1
Status: FAILURE
````
**Steps to Reproduce**  
When a policy is used which has a license group with "Requires Review" present

**Expected Behavior**  
should be copied as other licenses

**Environment Details**  
last version.

**Comment by thestift** [comment]
Hi @NatalyaDalid ,
I used the following script to install ws_copy_policy:
pip install --no-cache-dir ws-copy-policy==0.2.2
So I think I have the latest version running.
`````
 Step 4/6 : RUN pip install --no-cache-dir ws-copy-policy==0.2.2     && mkdir /copy_policy
  ---> Running in 324ba7757f6f
 Collecting ws-copy-policy==0.2.2
   Downloading ws_copy_policy-0.2.2-py3-none-any.whl (11 kB)
 Collecting configparser~=5.0.1
   Downloading configparser-5.0.2-py3-none-any.whl (19 kB)
 Collecting requests~=2.25.1
   Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
 Collecting certifi>=2017.4.17
   Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
 Collecting chardet<5,>=3.0.2
   Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
 Collecting urllib3<1.27,>=1.21.1
   Downloading urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
 Collecting idna<3,>=2.5
   Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
 Installing collected packages: urllib3, idna, chardet, certifi, requests, configparser, ws-copy-policy
 Successfully installed certifi-2021.10.8 chardet-4.0.0 configparser-5.0.2 idna-2.10 requests-2.25.1 urllib3-1.26.8 ws-copy-policy-0.2.2
````
regards,
the_stift

**Comment by rammatzkvosky** [comment]
Hi @thestift ,
We released a new version which fixes the reported issue : 
https://pypi.org/project/ws-copy-policy/0.2.3/

Please notice that the fix also provides a workaround for another bug ( being handled by our application team ) - if a reassign policy is set to some group and the group was removed afterwards - the reassign group will be changed to 'null'.

![image](https://user-images.githubusercontent.com/41573396/157238380-f0b8600e-b378-4510-8e59-f5eae3f00021.png)

In such case the copy-policy tool won't copy that specific policy and a message will be logged for that.
For now ,If you have any reassign policy which is set to a 'null' group , change it to an existing group.

Please let us know if the new version works for you as expected.

**Comment by thestift** [comment]
Hi @rammatzkvosky,
I haven't checked it yet, but from the code side it's seems you are just ignoring the license "Requires Review" which I think has id -1. So this won't be copied over with the other licenses - am I correct with my assumption?

**Comment by rammatzkvosky** [comment]
Hi @thestift ,

The mentioned  id is under the filter-license attribute which is [not requiered to add policy](https://whitesource.atlassian.net/wiki/spaces/WD/pages/1522630711/Policies+API#Project.1).

In general , the fix we implemented is a specific workaround for the copy policy tool to overcome an issue of adding a policy with  filter , license =-1 in the WS application ( which was already addressed internally to our application team ).

For example , here is [getProjectPolicies](https://whitesource.atlassian.net/wiki/spaces/WD/pages/1522630711/Policies+API#Project) output of a Requires Review policy which was generated from a template using the copy policy tool.
Under the filter attribute it  got id -1 automatically .

```
{
  "policies": [
    {
      "id": 70371,
      "name": "rr_policy",
      "owner": {
        "id": 6899,
        "email": "ram.matzkovsky@whitesourcesoftware.com",
        "name": "Ram Matzkovsky"
      },
      "creationTime": "2022-03-10",
      "priority": 1,
      "filter": {
        "type": "LICENSE",
        "licenses": [
          {
            "id": -1,
            "name": "Requires Review"
          }
        ],
        "scoreFrom": 0.0,
        "scoreTo": 0.0
      },
      "inclusive": false,
      "action": {
        "type": "REASSIGN",
        "user": {
          "id": 6899,
          "email": "ram.matzkovsky@whitesourcesoftware.com",
          "name": "Ram Matzkovsky"
        },
        "failPolicyCheck": false
      },
      "productLevel": false,
      "enabled": true,
      "policyContextName": "test_proj_2",
      "policyContextToken": "3ebf49d801bf4fc58fd8f09a05ec9da2f2b93c397cc94f9a91da3f48aa4250ce",
      "policyContext": "PROJECT"
    }
  ]
}
```

Please check the latest version and update if you faced any issues.

**Comment by thestift** [comment]
thanks a lot for the explanation !
