### ISSUE TITLE
[Question] [ws-copy-policy] Json Decode Error as response contains error Post method not supported

### ISSUE THREAD

**Issue by saiprashanthramasetti** [whitesource-ps/ws-copy-policy#8]
**Question**  
I am using this tool for first time. When running it with project level scope I get Json Decode Error as the response contains no JSON content to parse. I checked the content of the server response and it gives back HTTP method POST is not supported by this URL. Any ideas on how to address this issue?

2021-09-09 12:09:19,496 - Starting
2021-09-09 12:09:19,496 - Validating parameters
2021-09-09 12:09:19,498 - Using url https://app.whitesourcesoftware.com
2021-09-09 12:09:19,499 - Start getOrganizationProjectTags api
2021-09-09 12:09:19,926 - Finish getOrganizationProjectTags api
"<html><head><title>Error</title></head><body>HTTP method POST is not supported by this URL</body></html>"
Traceback (most recent call last):
  File "ws-copy-policy.py", line 318, in <module>
    main()
  File "ws-copy-policy.py", line 87, in main
    get_policies()
  File "ws-copy-policy.py", line 105, in get_policies
    scope_tags = post_request(request_type, body)
  File "ws-copy-policy.py", line 154, in post_request
    response_object = json.loads(response.text)
  File "C:\Program Files\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by NatalyaDalid** [comment]
Hello @saiprashanthramasetti,
Thank you for letting us know about your issue.

Looks like the URL is missing **/api** at the end. Please, configure wsUrl like **https://app.whitesourcesoftware.com/api** and try again. 
Please, let us know if there is anything else we can help with.

Thanks,
WhiteSource PS team

**Comment by saiprashanthramasetti** [comment]
Thanks Natalya, that helped but here's another issue I have while running the script. I am running script to copy Issue type policies. The script is giving back error code:3000, invalid request parameters.

here's the body sent in add_policies_from_template_to_target function. Is WS API expecting this req body because I did not find some values it in API documentation (I tried the req body in Postman and still get the same response). 

{'requestType': 'addProjectPolicy', 'userKey': 'user_id', 'projectToken': 'project_token', 'policy': {'name': 'Library Vulnerability', 'owner': {'id': id, 'email': 'email_id', 'name': 'name'}, 'priority': 3, 'filter': {'type': 'VULNERABILITY_SEVERITY', 'vulnerabilitySeverity': 'HIGH', 'scoreFrom': 0.0, 'scoreTo': 0.0}, 'inclusive': False, 'action': {'type': 'CREATE_ISSUE', 'failPolicyCheck': False}, 'productLevel': False, 'enabled': True, 'policyContextName': 'PolicyCopy', 'policyContextToken': 'b11660d54bd94a3eb21ac8930b9f578db278bb6a212f4db69b22a6b9815df797', 'policyContext': 'PROJECT'}}

**Comment by NatalyaDalid** [comment]
Hi @saiprashanthramasetti,
From the request body, you have sent I can see the value for the userKey is a user_id. Please make sure that this value is indeed a WhiteSource userKey (can be found under the 'Profile' section in your WhiteSource organization). In addition, please verify you are using the userKey which has Admin permissions.
If there is a case and it is still not working, please reach out directly to our PS team, by email ps@whitesourcesoftware.com, so we will be able to debug your specific case.

Thanks,
PS Team

**Comment by NatalyaDalid** [comment]
Hi @saiprashanthramasetti,

The fix has been provided, and the new release is now available.
Please note, now you can also install it from PyPI.

Thank you for this finding.

Regards,
Natalya
